function sp_side = sp_normal_tang_circ(space, msh, normal, varargin)

gradient = false;
hessian = false;
der3 = false;
if (~isempty (varargin))
  if (~rem (length (varargin), 2) == 0)
    error ('sp_evaluate_col_param: options must be passed in the [option, value] format');
  end
  for ii=1:2:length(varargin)-1
    if (strcmpi (varargin {ii}, 'gradient'))
      gradient = varargin {ii+1};
    elseif (strcmpi (varargin {ii}, 'hessian'))
        hessian = varargin {ii+1};
    elseif (strcmpi (varargin {ii}, 'der3'))
        der3 = varargin {ii+1};
    else
      error ('sp_evaluate_col_param: unknown option %s', varargin {ii});
    end
  end
end

%% NORMAL AND TANGENT VECTOR

% Comp. along x
nx = repmat(msh.normal(1,:,:), space.nsh_max, 1);
nx = reshape(nx, msh.nqn, space.nsh_max, msh.nel);
% Comp. along y
ny = repmat(msh.normal(2,:,:), space.nsh_max, 1);
ny = reshape(ny, msh.nqn, space.nsh_max, msh.nel);
% Tangential vector
tx = -ny;
ty = nx;



%%

if (gradient)
  % NORMAL AND TANGENT DERIVATIVES
  u_x = reshape(space.shape_function_gradients(1,:,:,:), msh.nqn, space.nsh_max, msh.nel);
  u_y = reshape(space.shape_function_gradients(2,:,:,:), msh.nqn, space.nsh_max, msh.nel);
  
  sp_side.deriv_normal(1,:,:,:) = u_x .* nx + u_y .* ny;    % Normal Derivative
  sp_side.deriv_normal(2,:,:,:) = u_x .* tx + u_y .* ty;    % Tangent Derivative
end
                           
if (hessian)
    %% NORMAL DERIV (n,i)
    nx_x = repmat(normal.deriv(1,1,:,:), space.nsh_max, 1);
    nx_x = reshape(nx_x, msh.nqn, space.nsh_max, msh.nel);
    %
    nx_y = repmat(normal.deriv(1,2,:,:), space.nsh_max, 1);
    nx_y = reshape(nx_y, msh.nqn, space.nsh_max, msh.nel);
    %
    ny_x = repmat(normal.deriv(2,1,:,:), space.nsh_max, 1);
    ny_x = reshape(ny_x, msh.nqn, space.nsh_max, msh.nel);
    %
    ny_y = repmat(normal.deriv(2,2,:,:), space.nsh_max, 1);
    ny_y = reshape(ny_y, msh.nqn, space.nsh_max, msh.nel);
    %
    tx_x = -ny_x; 
    tx_y = -ny_y;
    ty_x = nx_x;
    ty_y = nx_y;
    
    % SECOND NORMAL AND TANGENT DERIVATIVES
    u_xx = reshape(space.shape_function_hessians(1,1,:,:,:), msh.nqn, space.nsh_max, msh.nel);
    u_xy = reshape(space.shape_function_hessians(1,2,:,:,:), msh.nqn, space.nsh_max, msh.nel);
    u_yy = reshape(space.shape_function_hessians(2,2,:,:,:), msh.nqn, space.nsh_max, msh.nel);
     
    % R_nn
    sp_side.deriv2_normal(1,:,:,:) = (u_xx.*nx + u_x.*nx_x + u_xy.*ny + u_y.*ny_x).*nx +...
    (u_xy.*nx + u_x.*nx_y + u_yy.*ny + u_y.*ny_y).*ny;     
    
    % R_nt & R_tn
    sp_side.deriv2_normal(2,:,:,:) = (u_xx.*nx + u_x.*nx_x + u_xy.*ny + u_y.*ny_x).*tx +...
    (u_xy.*nx + u_x.*nx_y + u_yy.*ny + u_y.*ny_y).*ty;

    % R_tt
    sp_side.deriv2_normal(3,:,:,:) = (u_xx.*tx + u_x.*tx_x + u_xy.*ty + u_y.*ty_x).*tx +...
    (u_xy.*tx + u_x.*tx_y + u_yy.*ty + u_y.*ty_y).*ty;
end
  
if(der3)
    %% NORMAL DERIV (n,ij)
    nx_xx = repmat(normal.deriv2(1,1,:,:), space.nsh_max, 1);
    nx_xx = reshape(nx_xx, msh.nqn, space.nsh_max, msh.nel);
    %
    nx_xy = repmat(normal.deriv2(1,2,:,:), space.nsh_max, 1);
    nx_xy = reshape(nx_xy, msh.nqn, space.nsh_max, msh.nel);
    %
    nx_yy = repmat(normal.deriv2(1,3,:,:), space.nsh_max, 1);
    nx_yy = reshape(nx_yy, msh.nqn, space.nsh_max, msh.nel);
    %
    ny_xx = repmat(normal.deriv2(2,1,:,:), space.nsh_max, 1);
    ny_xx = reshape(ny_xx, msh.nqn, space.nsh_max, msh.nel);
    %
    ny_xy = repmat(normal.deriv2(2,2,:,:), space.nsh_max, 1);
    ny_xy = reshape(ny_xy, msh.nqn, space.nsh_max, msh.nel);
    %
    ny_yy = repmat(normal.deriv2(2,3,:,:), space.nsh_max, 1);
    ny_yy = reshape(ny_yy, msh.nqn, space.nsh_max, msh.nel);
    %
    tx_xx = -ny_xx; 
    tx_xy = -ny_xy;
    tx_yy = -ny_yy;
    %
    ty_xx = nx_xx;
    ty_xy = nx_xy;
    ty_yy = nx_yy;
    
    u_xxx = reshape(space.shape_function_der3(1,1,:,:,:), msh.nqn, space.nsh_max, msh.nel);
    u_xxy = reshape(space.shape_function_der3(1,2,:,:,:), msh.nqn, space.nsh_max, msh.nel);
    u_xyy = reshape(space.shape_function_der3(2,1,:,:,:), msh.nqn, space.nsh_max, msh.nel);
    u_yyy = reshape(space.shape_function_der3(2,2,:,:,:), msh.nqn, space.nsh_max, msh.nel);
    
    % THIRD NORMAL AND TANGENT DERIVATIVES
    % R_nnn
    sp_side.deriv3_normal(1,:,:,:) = ...
    (u_xxx.*nx + u_xx.*nx_x + u_xxy.*ny + u_xy.*ny_x).*nx.^2 +...
    (u_xxy.*nx + u_xy.*nx_x + u_xyy.*ny + u_yy.*ny_x).*nx.*ny +...
    (u_xxy.*nx + u_xx.*nx_y + u_xyy.*ny + u_xy.*ny_y).*nx.*ny +...
    (u_xyy.*nx + u_xy.*nx_y + u_yyy.*ny + u_yy.*ny_y).*ny.^2 +...
    (u_xx.*nx_x + u_x.*nx_xx + u_xy.*ny_x + u_y.*ny_xx).*nx.^2 +...
    (u_xx.*nx_y + u_x.*nx_xy + u_xy.*ny_y + u_y.*ny_xy).*nx.*ny +...
    (u_xy.*nx_x + u_x.*nx_xy + u_yy.*ny_x + u_y.*ny_xy).*nx.*ny +...
    (u_xy.*nx_y + u_x.*nx_yy + u_yy.*ny_y + u_y.*ny_yy).*ny.^2 +...
    (u_xx.*nx + u_x.*nx_x + u_xy.*ny + u_y.*ny_x).*nx_x.*nx +...
    (u_xx.*nx + u_x.*nx_x + u_xy.*ny + u_y.*ny_x).*nx_y.*ny +...
    (u_xy.*nx + u_x.*nx_y + u_yy.*ny + u_y.*ny_y).*ny_x.*nx +...
    (u_xy.*nx + u_x.*nx_y + u_yy.*ny + u_y.*ny_y).*ny_y.*ny;
    
    % R_nnt & R_ntn % R_tnn
    sp_side.deriv3_normal(2,:,:,:) = ...
    (u_xxx.*nx + u_xx.*nx_x + u_xxy.*ny + u_xy.*ny_x).*nx.*tx +...
    (u_xxy.*nx + u_xy.*nx_x + u_xyy.*ny + u_yy.*ny_x).*nx.*ty +...
    (u_xxy.*nx + u_xx.*nx_y + u_xyy.*ny + u_xy.*ny_y).*nx.*ty +...
    (u_xyy.*nx + u_xy.*nx_y + u_yyy.*ny + u_yy.*ny_y).*ny.*ty +...
    (u_xx.*nx_x + u_x.*nx_xx + u_xy.*ny_x + u_y.*ny_xx).*nx.*tx +...
    (u_xx.*nx_y + u_x.*nx_xy + u_xy.*ny_y + u_y.*ny_xy).*nx.*ty +...
    (u_xy.*nx_x + u_x.*nx_xy + u_yy.*ny_x + u_y.*ny_xy).*nx.*ty +...
    (u_xy.*nx_y + u_x.*nx_yy + u_yy.*ny_y + u_y.*ny_yy).*ny.*ty +...
    (u_xx.*nx + u_x.*nx_x + u_xy.*ny + u_y.*ny_x).*nx_x.*tx +...
    (u_xx.*nx + u_x.*nx_x + u_xy.*ny + u_y.*ny_x).*nx_y.*ty +...
    (u_xy.*nx + u_x.*nx_y + u_yy.*ny + u_y.*ny_y).*ny_x.*tx +...
    (u_xy.*nx + u_x.*nx_y + u_yy.*ny + u_y.*ny_y).*ny_y.*ty;
    
    % R_ntt & R_ttn & R_tnt
    sp_side.deriv3_normal(3,:,:,:) = ...
    (u_xxx.*tx + u_xx.*tx_x + u_xxy.*ty + u_xy.*ty_x).*tx.*nx +...
    (u_xxy.*tx + u_xy.*tx_x + u_xyy.*ty + u_yy.*ty_x).*tx.*ny +...
    (u_xxy.*tx + u_xx.*tx_y + u_xyy.*ty + u_xy.*ty_y).*tx.*ny +...
    (u_xyy.*tx + u_xy.*tx_y + u_yyy.*ty + u_yy.*ty_y).*ty.*ny +...
    (u_xx.*tx_x + u_x.*tx_xx + u_xy.*ty_x + u_y.*ty_xx).*tx.*nx +...
    (u_xx.*tx_y + u_x.*tx_xy + u_xy.*ty_y + u_y.*ty_xy).*tx.*ny +...
    (u_xy.*tx_x + u_x.*tx_xy + u_yy.*ty_x + u_y.*ty_xy).*tx.*ny +...
    (u_xy.*tx_y + u_x.*tx_yy + u_yy.*ty_y + u_y.*ty_yy).*ty.*ny +...
    (u_xx.*tx + u_x.*tx_x + u_xy.*ty + u_y.*ty_x).*tx_x.*nx +...
    (u_xx.*tx + u_x.*tx_x + u_xy.*ty + u_y.*ty_x).*tx_y.*ny +...
    (u_xy.*tx + u_x.*tx_y + u_yy.*ty + u_y.*ty_y).*ty_x.*nx +...
    (u_xy.*tx + u_x.*tx_y + u_yy.*ty + u_y.*ty_y).*ty_y.*ny;
     
    % R_ttt
    sp_side.deriv3_normal(4,:,:,:) = ...
    (u_xxx.*tx + u_xx.*tx_x + u_xxy.*ty + u_xy.*ty_x).*tx.^2 +...
    (u_xxy.*tx + u_xy.*tx_x + u_xyy.*ty + u_yy.*ty_x).*tx.*ty +...
    (u_xxy.*tx + u_xx.*tx_y + u_xyy.*ty + u_xy.*ty_y).*tx.*ty +...
    (u_xyy.*tx + u_xy.*tx_y + u_yyy.*ty + u_yy.*ty_y).*ty.^2 +...
    (u_xx.*tx_x + u_x.*tx_xx + u_xy.*ty_x + u_y.*ty_xx).*tx.^2 +...
    (u_xx.*tx_y + u_x.*tx_xy + u_xy.*ty_y + u_y.*ty_xy).*tx.*ty +...
    (u_xy.*tx_x + u_x.*tx_xy + u_yy.*ty_x + u_y.*ty_xy).*tx.*ty +...
    (u_xy.*tx_y + u_x.*tx_yy + u_yy.*ty_y + u_y.*ty_yy).*ty.^2 +...
    (u_xx.*tx + u_x.*tx_x + u_xy.*ty + u_y.*ty_x).*tx_x.*tx +...
    (u_xx.*tx + u_x.*tx_x + u_xy.*ty + u_y.*ty_x).*tx_y.*ty +...
    (u_xy.*tx + u_x.*tx_y + u_yy.*ty + u_y.*ty_y).*ty_x.*tx +...
    (u_xy.*tx + u_x.*tx_y + u_yy.*ty + u_y.*ty_y).*ty_y.*ty;
end

% Copy structure of space
sp_side.nsh_max = space.nsh_max;
sp_side.nsh = space.nsh;
sp_side.ndof = space.ndof;
sp_side.ndof_dir = space.ndof_dir;
sp_side.connectivity = space.connectivity;
sp_side.ncomp = space.ncomp;

end


% % VERIFICA DA MATHEMATICA!!
% sp_side.deriv3_normal(1,:,:,:) =...
%     u_xxx.*nx.^3 + u_yyy.*ny.^3 + 3.*u_xxy.*nx.^2.*ny + 3.*u_xyy.*nx.*ny.^2+...
%     u_xx.*nx_x.*nx.^2 + u_xx.*nx_y.*nx.*ny + u_xy.*nx_x.*nx.*ny +...
%     u_xy.*nx_y.*ny.^2 + u_xy.*ny_x.*nx.^2 + u_xy.*ny_y.*nx.*ny + u_yy.*ny_x.*nx.*ny + u_yy.*ny_y.*ny.^2+...
%     u_xx.*nx_x.*nx.^2 + u_xx.*nx_y.*nx.*ny + u_xy.*ny_x.*nx.^2 +...
%     u_xy.*ny_y.*nx.*ny + u_xy.*nx_x.*nx.*ny + u_xy.*nx_y.*ny.^2+...
%     u_yy.*ny_x.*nx.*ny + u_yy.*ny_y.*ny.^2+...
%     u_xx.*nx_x.*nx.^2 + u_xx.*nx_y.*nx.*ny + u_xy.*nx_x.*nx.*ny+...
%     u_xy.*nx_y.*ny.^2 + u_xy.*ny_x.*nx.^2 + u_xy.*ny_y.*nx.*ny +...
%     u_yy.*ny_x.*nx.*ny + u_yy.*ny_y.*ny.^2 +...
%     u_x.*nx_xx.*nx.^2 + u_x.*nx_xy.*nx.*ny + u_x.*nx_xy.*nx.*ny+...
%     u_x.*nx_yy.*ny.^2 + u_y.*ny_xx.*nx.^2 + u_y.*ny_xy.*nx.*ny+...
%     u_y.*ny_xy.*nx.*ny + u_y.*ny_yy.*ny.^2 +...
%     u_x.*nx_x.^2.*nx + u_x.*nx_y.*nx_x.*ny + u_x.*ny_x.*nx_y.*nx +...
%     u_x.*ny_y.*nx_y.*ny + u_y.*ny_x.*nx_x.*nx +...
%     u_y.*ny_x.*nx_y.*ny + u_y.*ny_y.*ny_x.*nx + u_y.*ny_y.^2.*ny; 